# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialStorage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking'
  pod 'InstagramKit'
  pod 'FBSDKCoreKit'
  pod 'VK-ios-sdk'
  pod 'FontAwesomeKit'

  # Pods for SocialStorage

  target 'SocialStorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocialStorageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
